-- MySQL Script generated by MySQL Workbench
-- Thu Dec 19 13:12:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema game2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema game2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `game2` DEFAULT CHARACTER SET utf8 ;
USE `game2` ;

-- -----------------------------------------------------
-- Table `game2`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Planet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Planet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL DEFAULT 'Kolonie',
  `size` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `material` INT NOT NULL,
  `electronics` INT NOT NULL,
  `fuel` INT NOT NULL,
  `rocketlauncher` INT NULL,
  `lasergun` INT NULL,
  `iongun` INT NULL,
  `shockwavecannon` INT NULL,
  `plasmacannon` INT NULL,
  `antimatterradiator` INT NULL,
  `spacemines` INT NULL,
  `planetshield` INT NULL,
  `scout` INT NULL,
  `hunter` INT NULL,
  `cruiser` INT NULL,
  `zerstörer` INT NULL,
  `battleship` INT NULL,
  `bomber` INT NULL,
  `mothership` INT NULL,
  `colonisationship` INT NULL,
  `mine` INT NULL,
  `factory` INT NULL,
  `oilrig` INT NULL,
  `fueltank` INT NULL,
  `materialstorage` INT NULL,
  `electronicstorage` INT NULL,
  `spaceshipyard` INT NULL,
  `cyborgfactory` INT NULL,
  `researchfacility` INT NULL,
  `powerplant` INT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Planet_Account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_planet_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `game2`.`Account` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Fleets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Fleets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hunter` INT NULL,
  `cruiser` INT NULL,
  `destroyer` INT NULL,
  `scout` INT NULL,
  `colonisationship` INT NULL,
  `battleship` INT NULL,
  `bomber` INT NULL,
  `mothership` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Research` (
  `industry` INT NOT NULL DEFAULT 0,
  `engine` INT NOT NULL DEFAULT 0,
  `weapon` INT NOT NULL DEFAULT 0,
  `shield` INT NOT NULL DEFAULT 0,
  `materialeffiency` INT NOT NULL DEFAULT 0,
  `laser` INT NOT NULL DEFAULT 0,
  `Account_id` INT NOT NULL,
  PRIMARY KEY (`Account_id`),
  CONSTRAINT `fk_Forschung_Account1`
    FOREIGN KEY (`Account_id`)
    REFERENCES `game2`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Attacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Attacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `destinationx` INT NOT NULL,
  `destinationy` INT NOT NULL,
  `startx` INT NOT NULL,
  `starty` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Researches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Researches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Researchdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Researchdata` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` INT NOT NULL,
  `bonus` INT NOT NULL,
  `material` INT NOT NULL,
  `chips` INT NOT NULL,
  `fuel` INT NOT NULL,
  `forschungen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_forschungsdaten_forschungen_idx` (`forschungen_id` ASC) VISIBLE,
  CONSTRAINT `fk_forschungsdaten_forschungen`
    FOREIGN KEY (`forschungen_id`)
    REFERENCES `game2`.`Researches` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Shipdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Shipdata` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `hitpoints` INT NULL,
  `angriff` INT NULL,
  `shields` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Production` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game2`.`Productiondata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game2`.`Productiondata` (
  `id` INT NOT NULL,
  `level` INT NOT NULL,
  `output` INT NOT NULL,
  `Production_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Abbaudaten_Abbau1_idx` (`Production_id` ASC) VISIBLE,
  CONSTRAINT `fk_Abbaudaten_Abbau1`
    FOREIGN KEY (`Production_id`)
    REFERENCES `game2`.`Production` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
