-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 15:35:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planet` (
  `id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL DEFAULT 'Kolonie',
  `size` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `metall` INT NOT NULL,
  `platinen` INT NOT NULL,
  `treibstoff` INT NOT NULL,
  `Account_id` INT NOT NULL,
  `verteidigung1` INT NULL,
  `verteidigung2` INT NULL,
  `verteidigung3` INT NULL,
  `gebaeude1` INT NULL,
  `gebaeude2` INT NULL,
  `gebaeude3` INT NULL,
  `abbau1` INT NULL,
  `abbau2` INT NULL,
  `abbau3` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Planet_Account_idx` (`Account_id` ASC),
  CONSTRAINT `fk_Planet_Account`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flotte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flotte` (
  `id` INT NOT NULL,
  `jaeger` INT NOT NULL,
  `kreuzer` INT NOT NULL,
  `zerstörer` INT NOT NULL,
  `zielplanet` INT NULL,
  `Planet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Flotte_Planet1_idx` (`Planet_id` ASC),
  CONSTRAINT `fk_Flotte_Planet1`
    FOREIGN KEY (`Planet_id`)
    REFERENCES `mydb`.`Planet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forschung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forschung` (
  `forschung1` INT NOT NULL,
  `forschung2` INT NOT NULL,
  `forschung3` INT NOT NULL,
  `Account_id` INT NOT NULL,
  PRIMARY KEY (`Account_id`),
  CONSTRAINT `fk_Forschung_Account1`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
