package com.example.strategiespielapp;

public class AccountPlanet {
    int accountId;
    String email;
    String username;
    String password;
    long last_online;
    int planetId;
    String name;
    int size;
    int temperature;
    int x;
    int y;
    int material;
    int electronics;
    int fuel;
    int rocketlauncher;
    int lasergun;
    int iongun;
    int shockwavecannon;
    int plasmacannon;
    int antimatterradiator;
    int spacemines;
    int planetshield;
    int scout;
    int hunter;
    int cruiser;
    int battleship;
    int destroyer;
    int bomber;
    int mothership;
    int colonisationship;
    int mine;
    int factory;
    int oilrig;
    int fueltank;
    int materialstorage;
    int electronicstorage;
    int spaceshipyard;
    int cyborgfactory;
    int researchfacility;
    int powerplant;
    int account_Id;

    public AccountPlanet(int accountId, String email, String username, String password, long last_online, int planetId, String name, int size, int temperature, int x, int y, int material, int electronics, int fuel, int rocketlauncher, int lasergun, int iongun, int shockwavecannon, int plasmacannon, int antimatterradiator, int spacemines, int planetshield, int scout, int hunter, int cruiser, int battleship, int destroyer, int bomber, int mothership, int colonisationship, int mine, int factory, int oilrig, int fueltank, int materialstorage, int electronicstorage, int spaceshipyard, int cyborgfactory, int researchfacility, int powerplant, int account_Id) {
        this.accountId = accountId;
        this.email = email;
        this.username = username;
        this.password = password;
        this.last_online = last_online;
        this.planetId = planetId;
        this.name = name;
        this.size = size;
        this.temperature = temperature;
        this.x = x;
        this.y = y;
        this.material = material;
        this.electronics = electronics;
        this.fuel = fuel;
        this.rocketlauncher = rocketlauncher;
        this.lasergun = lasergun;
        this.iongun = iongun;
        this.shockwavecannon = shockwavecannon;
        this.plasmacannon = plasmacannon;
        this.antimatterradiator = antimatterradiator;
        this.spacemines = spacemines;
        this.planetshield = planetshield;
        this.scout = scout;
        this.hunter = hunter;
        this.cruiser = cruiser;
        this.battleship = battleship;
        this.destroyer = destroyer;
        this.bomber = bomber;
        this.mothership = mothership;
        this.colonisationship = colonisationship;
        this.mine = mine;
        this.factory = factory;
        this.oilrig = oilrig;
        this.fueltank = fueltank;
        this.materialstorage = materialstorage;
        this.electronicstorage = electronicstorage;
        this.spaceshipyard = spaceshipyard;
        this.cyborgfactory = cyborgfactory;
        this.researchfacility = researchfacility;
        this.powerplant = powerplant;
        this.account_Id = account_Id;
    }
}
